import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Coffee, Instagram, MapPin, Menu, MessageCircle, Nfc, Package, Palette, Scissors, ShieldCheck, ShoppingBag, Smartphone, Sparkles, Store, Truck, Utensils, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ContactButton, Demo, InquiryForm, ProductPhoto } from '@/components/tap-experience';
import { navigation, tapReview, whatsapp } from '@/lib/tap-review';
import { PremiumCatalog, PremiumPack, PremiumPersonalization } from '@/components/premium-catalog';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Tap Review | Tarjetas NFC para negocios' },
    { name: 'description', content: 'Tarjetas NFC personalizadas para negocios. Conectá a tus clientes con Google e Instagram con un simple toque. Tap Review San Juan.' },
    { property: 'og:title', content: 'Tap Review | Tarjetas NFC para negocios' },
    { property: 'og:description', content: 'Tarjetas NFC personalizadas para negocios. Conectá a tus clientes con Google e Instagram con un simple toque. Tap Review San Juan.' },
    { property: 'og:type', content: 'website' },
    { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: Index,
});

const categories = [
  { name: 'Restaurantes', icon: Utensils, text: 'Facilitá el acceso a tus reseñas.' },
  { name: 'Cafeterías', icon: Coffee, text: 'Convertí una experiencia en una conexión.' },
  { name: 'Barberías', icon: Scissors, text: 'Tu cliente termina el corte y puede encontrarte en Instagram con un toque.' },
  { name: 'Tiendas', icon: ShoppingBag, text: 'Conectá tu local físico con tus redes.' },
  { name: 'Emprendimientos', icon: Store, text: 'Llevá tu presencia digital a donde está tu cliente.' },
] as const;

function Index() {
  const [menu, setMenu] = useState(false);
  const [compact, setCompact] = useState(false);
  useEffect(() => {
    const scroll = () => setCompact(window.scrollY > 40);
    window.addEventListener('scroll', scroll, { passive: true });
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .1 });
    document.querySelectorAll('.reveal').forEach((node) => observer.observe(node));
    return () => { observer.disconnect(); window.removeEventListener('scroll', scroll); };
  }, []);
  useEffect(() => {
    if (!menu) return;
    const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenu(false); };
    window.addEventListener('keydown', listener);
    return () => window.removeEventListener('keydown', listener);
  }, [menu]);
  return <>
    <header className={`navbar ${compact ? 'compact' : ''}`}><div className="container nav-inner"><a href="#inicio" className="wordmark" aria-label="Tap Review inicio">TAP REVIEW<span className="logo-tap"><Nfc /></span></a><nav className="desktop-nav" aria-label="Navegación principal">{navigation.map(([label, id]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="nav-actions"><a href={tapReview.instagram} target="_blank" rel="noopener noreferrer" className="nav-instagram" aria-label="Instagram Tap Review"><Instagram size={19} /></a><ContactButton /><Button variant="ghost" size="icon" className="mobile-toggle" aria-label={menu ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menu} aria-controls="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</Button></div></div>{menu && <nav id="mobile-menu" className="mobile-nav" aria-label="Navegación móvil">{navigation.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}<ArrowUpRight size={18} /></a>)}<a href={tapReview.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18} />@tap.review_sj</a><ContactButton /></nav>}</header>
    <main>
      <section className="hero" id="inicio"><div className="container hero-layout"><div className="hero-copy"><span className="eyebrow"><span className="status-dot" />DE SAN JUAN, PARA TU NEGOCIO</span><h1>TAP REVIEW</h1><h2>Tu negocio.<br />Un toque más cerca<br /> de tus clientes.</h2><p>Tarjetas NFC personalizadas para conectar tu negocio con Google e Instagram de una forma rápida, simple y profesional.</p><div className="hero-actions"><Button asChild className="tap-button hero-primary"><a href="#productos">Ver productos<ArrowDown size={17} /></a></Button><ContactButton secondary /></div><div className="hero-notes"><span><Nfc />Un toque, una conexión</span><span><Palette />Personalizadas para vos</span></div></div><div className="hero-visual"><div className="product-orbit" /><ProductPhoto className="hero-google" product="Google" /><ProductPhoto className="hero-photo" /><span className="photo-caption"><span className="caption-line" />TU TARJETA. TU MARCA.</span><span className="hero-product-label">TARJETAS NFC PERSONALIZADAS <ArrowUpRight size={16} /></span></div></div><div className="container hero-bottom"><span>Menos búsquedas. Más conexiones.</span><a href="#que-es">Conocé Tap Review<ArrowDown size={16} /></a></div></section>
      <div className="connection-strip"><div className="container"><span>Tu negocio físico.<strong>Tu mundo digital.</strong></span><span className="platform"><span className="google-mark">G</span>Google Reviews</span><span className="platform"><Instagram />Instagram</span><span className="strip-end"><Nfc />Conectados por un toque</span></div></div>
      <section className="section intro-section" id="que-es"><div className="container intro-grid reveal"><div><span className="eyebrow">UNA TARJETA. MUCHAS CONEXIONES.</span><h2>¿Qué es<br /> Tap Review?</h2></div><div><p className="large-copy">Una forma simple de conectar tu local con la presencia digital de tu negocio.</p><p>Tap Review crea tarjetas NFC personalizadas para negocios que quieren facilitar la interacción con sus clientes.</p><p>Con un simple toque del celular, tus clientes pueden acceder rápidamente a tu perfil de Google para dejar una reseña o entrar directamente a tu Instagram. No necesitan buscar el negocio manualmente ni escribir nombres de usuario.</p><div className="intro-flow"><Smartphone /><ArrowRight /><Nfc /><ArrowRight /><span>Tu negocio</span></div></div></div></section>
      <section className="section steps-section" id="como-funciona"><div className="container"><div className="section-heading reveal"><span className="eyebrow">NO HACE FALTA COMPLICARLO</span><h2>Acercá. Tocá. Conectá.</h2><p>Así funciona la tecnología NFC: una conexión sin contacto, con solo acercar el celular.</p></div><div className="steps-grid">{[{ title: 'Acercá', icon: Smartphone, text: 'El cliente acerca su celular a la tarjeta Tap Review.' }, { title: 'Tocá', icon: Nfc, text: 'El teléfono reconoce la tecnología NFC automáticamente.' }, { title: 'Conectá', icon: ArrowUpRight, text: 'El cliente accede directamente al destino configurado: Google o Instagram.' }].map((step, i) => <div className="step reveal" key={step.title}><div className="step-top"><span>0{i + 1}</span><step.icon /></div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div><p className="compatibility">El celular debe ser compatible con NFC y tener la función activada.</p></div></section>
      <PremiumCatalog />
      <PremiumPack />
      <PremiumPersonalization />
      <Demo />
      <section className="section audience-section"><div className="container"><div className="section-heading reveal"><span className="eyebrow">DETRÁS DE CADA NEGOCIO, HAY PERSONAS</span><h2>Pensado para negocios que<br />quieren conectar más fácil.</h2></div><div className="audience-grid">{categories.map((category) => <div key={category.name} className="audience-item reveal"><category.icon /><h3>{category.name}</h3><p>{category.text}</p></div>)}</div></div></section>
      <section className="section benefits-section"><div className="container"><div className="benefits-heading reveal"><span className="eyebrow">¿POR QUÉ TAP REVIEW?</span><h2>Lo simple también<br />hace la diferencia.</h2></div><div className="benefits-grid">{[{ name: 'Simple', icon: Check, text: 'Sin búsquedas innecesarias.' }, { name: 'Rápido', icon: Zap, text: 'Un toque y el cliente accede.' }, { name: 'Personalizado', icon: Palette, text: 'Diseñado para tu negocio.' }, { name: 'Profesional', icon: ShieldCheck, text: 'Una herramienta física que conecta tu local con tu presencia digital.' }].map((benefit) => <div key={benefit.name} className="benefit reveal"><benefit.icon /><h3>{benefit.name}</h3><p>{benefit.text}</p></div>)}</div></div></section>
      <section className="section process-section"><div className="container"><div className="section-heading reveal"><span className="eyebrow">DEL PRIMER MENSAJE A TU LOCAL</span><h2>Así de simple trabajamos.</h2></div><div className="timeline reveal">{[{ title: 'Nos contactás', text: 'Nos escribís por WhatsApp o Instagram.' }, { title: 'Elegís tu tarjeta', text: 'Google, Instagram o el Pack.' }, { title: 'Personalizamos', text: 'Adaptamos la tarjeta a la identidad de tu negocio.' }, { title: 'Coordinamos la entrega', text: 'La llevamos a tu local o coordinamos el envío.' }].map((step, i) => <div className="timeline-step" key={step.title}><span>0{i + 1}</span><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></div></section>
      <section className="section delivery-section"><div className="container delivery-grid"><div className="reveal"><span className="eyebrow">TU PEDIDO, A TU MANERA</span><h2>Lo coordinamos<br />con vos.</h2><p>Una vez que realizás tu pedido, coordinamos la entrega según tu ubicación.</p><ContactButton secondary>Consultar entrega</ContactButton></div><div className="delivery-options">{[{ name: 'Entrega en tu local', icon: Store, text: 'Podemos coordinar para llevar tu pedido directamente a tu negocio, según disponibilidad y zona.' }, { name: 'Envío', icon: Truck, text: 'También podemos coordinar el envío de tu Tap Review a domicilio.' }, { name: 'Coordinación', icon: MessageCircle, text: 'Escribinos por WhatsApp o Instagram y coordinamos juntos el pedido y la entrega.' }].map((option) => <div className="delivery-option reveal" key={option.name}><option.icon /><div><h3>{option.name}</h3><p>{option.text}</p></div></div>)}</div></div></section>
      <section className="section about-section" id="nosotros"><div className="container about-grid"><div className="about-brand reveal"><span className="eyebrow"><MapPin size={14} />SAN JUAN, ARGENTINA</span><span className="about-wordmark">TAP<br />REVIEW<span>↗</span></span><span>Un emprendimiento. Muchas conexiones.</span></div><div className="reveal"><span className="eyebrow">CERCA DE TU NEGOCIO</span><h2>Somos Tap Review.</h2><p>Somos un emprendimiento de San Juan enfocado en crear soluciones simples para que los negocios puedan conectar su presencia física con sus clientes digitales.</p><p>Creamos tarjetas NFC personalizadas que hacen que acceder a Google e Instagram sea mucho más rápido y sencillo.</p><p>Queremos que Tap Review sea una herramienta práctica, accesible y profesional para negocios de todo tipo.</p><a href={tapReview.instagram} className="text-link" target="_blank" rel="noopener noreferrer">Conocenos en Instagram<ArrowUpRight size={17} /></a></div></div></section>
      <section className="section contact-section" id="contacto"><div className="container contact-grid"><div className="reveal"><span className="eyebrow">ARRANQUEMOS CON UN MENSAJE</span><h2>¿Querés tu<br />Tap Review?</h2><p>Escribinos y te mostramos cómo quedaría para tu negocio.</p><div className="contact-links">{tapReview.phones.map((phone, i) => <a href={whatsapp(undefined, phone.number)} key={phone.number} target="_blank" rel="noopener noreferrer"><MessageCircle /><div><small>WHATSAPP {i + 1}</small><strong>{phone.label}</strong></div><ArrowUpRight /></a>)}<a href={tapReview.instagram} target="_blank" rel="noopener noreferrer"><Instagram /><div><small>INSTAGRAM</small><strong>@tap.review_sj</strong></div><ArrowUpRight /></a></div></div><InquiryForm /></div></section>
      <section className="final-section"><div className="container final-layout"><div className="reveal"><span className="eyebrow">UNA NUEVA FORMA DE CONECTAR</span><h2>¿LISTO PARA LLEVAR TAP REVIEW A TU NEGOCIO?</h2><p>Personalizá tu tarjeta y empezá a conectar con tus clientes en un solo toque.</p><div className="final-actions"><ContactButton /><ContactButton secondary>Hablar por WhatsApp</ContactButton></div></div><div className="final-photos"><ProductPhoto product="Google" /><ProductPhoto /></div></div></section>
    </main>
    <footer><div className="container footer-grid"><div><a href="#inicio" className="wordmark">TAP REVIEW<Nfc /></a><p>Tarjetas NFC personalizadas<br />para negocios.</p><span className="footer-location"><MapPin size={14} />San Juan, Argentina</span></div><nav aria-label="Navegación del pie">{navigation.map(([label, id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="footer-contact">{tapReview.phones.map((phone) => <a href={whatsapp(undefined, phone.number)} key={phone.number} target="_blank" rel="noopener noreferrer">{phone.label}<ArrowUpRight size={14} /></a>)}<a href={tapReview.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={16} />@tap.review_sj<ArrowUpRight size={14} /></a></div></div><div className="container footer-bottom"><span>© 2026 Tap Review. Todos los derechos reservados.</span><span>Hecho para conectar.</span></div></footer>
    <Button asChild size="icon" className="floating-whatsapp"><a href={whatsapp()} target="_blank" rel="noopener noreferrer" aria-label="Consultar por WhatsApp" title="Consultar por WhatsApp"><MessageCircle /></a></Button>
  </>;
}
